import { useCallback, useEffect, useRef } from "react";
import type { RefObject } from "react";
import "@xterm/xterm/css/xterm.css";
import { type ColorPalette, fonts } from "../theme";

// Inject a one-time style to hide the xterm scrollbar so the FitAddon
// uses the full container width (macOS overlay scrollbars report 0 width
// but the FitAddon may still reserve space).
let scrollbarStyleInjected = false;
function injectScrollbarStyle() {
  if (scrollbarStyleInjected) return;
  scrollbarStyleInjected = true;
  // Use the same scrollbar appearance as the rest of the app (set in ThemeContext).
  // Just ensure the xterm viewport doesn't hide it.
  const style = document.createElement("style");
  style.textContent = `.xterm-viewport { scrollbar-width: thin; }`;
  document.head.appendChild(style);
}

function buildXTermTheme(colors: ColorPalette) {
  const base = {
    background: colors.sidebar,
    foreground: colors.text,
    cursor: colors.cursor,
    cursorAccent: colors.isDark ? "#000000" : "#ffffff",
    selectionBackground: colors.isDark ? "#214283" : "#a6d2ff",
    selectionForeground: colors.isDark ? undefined : "#000000",
  };
  if (colors.isDark) return base;
  // Light theme: override ANSI palette so colors are readable on a light background.
  return {
    ...base,
    black: "#000000",
    red: "#cd3131",
    green: "#00864b",
    yellow: "#795e00",
    blue: "#0451a5",
    magenta: "#bc05bc",
    cyan: "#0598bc",
    white: "#555555",
    brightBlack: "#666666",
    brightRed: "#cd3131",
    brightGreen: "#14a860",
    brightYellow: "#b5a200",
    brightBlue: "#0451a5",
    brightMagenta: "#bc05bc",
    brightCyan: "#0598bc",
    brightWhite: "#333333",
  };
}

interface UseXTerminalOptions {
  containerRef: RefObject<HTMLDivElement | null>;
  colors: ColorPalette;
  fontSize?: number;
  onInput: (data: string) => void;
  onResize: (cols: number, rows: number) => void;
}

/**
 * Manages xterm.js lifecycle: lazy init, fit, resize observation, and cleanup.
 * Returns a `write` callback for pushing data into the terminal and a ref to
 * the underlying Terminal instance.
 */
export function useXTerminal({
  containerRef,
  colors,
  fontSize: termFontSize,
  onInput,
  onResize,
}: UseXTerminalOptions) {
  const xtermRef = useRef<import("@xterm/xterm").Terminal | null>(null);
  const fitAddonRef = useRef<import("@xterm/addon-fit").FitAddon | null>(null);

  const write = useCallback((data: Uint8Array | string) => {
    const term = xtermRef.current;
    if (!term) return;
    term.write(data, () => {
      // Always scroll to bottom after write. Claude CLI uses cursor
      // positioning for its status line which can leave the viewport
      // scrolled up.
      term.scrollToBottom();
    });
  }, []);

  const clear = useCallback(() => {
    xtermRef.current?.clear();
    xtermRef.current?.reset();
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    let disposed = false;

    async function init() {
      const { Terminal: XTerm } = await import("@xterm/xterm");
      const { FitAddon } = await import("@xterm/addon-fit");
      const { WebLinksAddon } = await import("@xterm/addon-web-links");

      if (disposed) return;

      const term = new XTerm({
        cursorBlink: true,
        fontSize: termFontSize ?? 13,
        fontFamily: fonts.mono,
        theme: buildXTermTheme(colors),
      });

      const fitAddon = new FitAddon();
      fitAddonRef.current = fitAddon;
      term.loadAddon(fitAddon);
      term.loadAddon(new WebLinksAddon());

      injectScrollbarStyle();
      term.open(containerRef.current!);

      // Pin scrollbar width to 8px (thin scrollbar).
      // Without this, xterm.js may compute 0 (macOS overlay) or 15px (default).
      const core = (term as any)._core;
      if (core?.viewport) {
        Object.defineProperty(core.viewport, "scrollBarWidth", {
          get: () => 8,
          set: () => {},
          configurable: true,
        });
      }

      fitAddon.fit();

      xtermRef.current = term;

      onResize(term.cols, term.rows);

      term.onData((data) => {
        // Filter out Cursor Position Report responses (ESC[row;colR)
        // generated by xterm.js in response to DSR queries (ESC[6n).
        if (/^\x1b\[\d+;\d+R$/.test(data)) return;
        onInput(data);
      });

      term.onResize(({ cols, rows }) => {
        onResize(cols, rows);
      });

      // Attach selection getter to the .xterm element so useCopyOnSelect can
      // read the selection on mouseup without a module-level singleton.
      const xtermEl = containerRef.current!.querySelector(".xterm") as
        | (Element & { _xtermGetSelection?: () => string })
        | null;

      // Manual drag-selection tracking for when mouse reporting is active
      // (e.g. Claude Code TUI). xterm forwards mouse events to PTY, so
      // term.getSelection() stays empty. We read the buffer directly like iTerm2.
      let dragSel = "";
      let dragStart: { col: number; row: number } | null = null;

      const getCellCoords = (clientX: number, clientY: number): { col: number; row: number } | null => {
        const core = (term as any)._core;
        const charW: number = core?._charSizeService?.width;
        const charH: number = core?._charSizeService?.height;
        if (!charW || !charH) return null;
        // Use .xterm-screen rect — this is what xterm uses internally for its
        // own selection coordinate calculations, correctly excluding any padding
        // between the outer container and the actual cell grid.
        const screenEl = container.querySelector(".xterm-screen");
        const rect = (screenEl ?? container).getBoundingClientRect();
        const col = Math.max(0, Math.min(term.cols - 1, Math.floor((clientX - rect.left) / charW)));
        const row = Math.max(0, Math.min(term.rows - 1, Math.floor((clientY - rect.top) / charH)));
        return { col, row };
      };

      const getBufferText = (
        startCol: number, startRow: number,
        endCol: number, endRow: number,
      ): string => {
        // startRow/endRow are viewport-relative; add viewportY to get buffer rows.
        const viewportY = term.buffer.active.viewportY;
        let r0 = startRow + viewportY;
        let c0 = startCol;
        let r1 = endRow + viewportY;
        let c1 = endCol;
        // Normalise so r0/c0 is before r1/c1.
        if (r0 > r1 || (r0 === r1 && c0 > c1)) {
          [r0, r1] = [r1, r0];
          [c0, c1] = [c1, c0];
        }
        const parts: string[] = [];
        for (let r = r0; r <= r1; r++) {
          const line = term.buffer.active.getLine(r);
          if (!line) continue;
          // translateToString(false) preserves full column width (no trimming),
          // so indices c0/c1 correspond exactly to cell positions.
          // trimEnd() then removes the trailing space padding.
          const full = line.translateToString(false);
          let seg: string;
          if (r === r0 && r === r1) {
            seg = full.slice(c0, c1 + 1);
          } else if (r === r0) {
            seg = full.slice(c0);
          } else if (r === r1) {
            seg = full.slice(0, c1 + 1);
          } else {
            seg = full;
          }
          parts.push(seg.trimEnd());
        }
        return parts.join("\n");
      };

      const container = containerRef.current!;

      const onDragMouseDown = (e: MouseEvent) => {
        // Only primary button; reset previous manual selection.
        if (e.button !== 0) return;
        dragSel = "";
        const coords = getCellCoords(e.clientX, e.clientY);
        dragStart = coords;
      };

      const onDragMouseUp = (e: MouseEvent) => {
        if (e.button !== 0 || !dragStart) return;
        const end = getCellCoords(e.clientX, e.clientY);
        if (!end) { dragStart = null; return; }
        // Only populate dragSel when the user actually dragged (not a plain click).
        if (end.col !== dragStart.col || end.row !== dragStart.row) {
          dragSel = getBufferText(dragStart.col, dragStart.row, end.col, end.row).trim();
        }
        dragStart = null;
      };

      container.addEventListener("mousedown", onDragMouseDown);
      // Capture phase so this fires before useCopyOnSelect's mouseup handler,
      // ensuring dragSel is populated when _xtermGetSelection is called.
      document.addEventListener("mouseup", onDragMouseUp, true);

      if (xtermEl) xtermEl._xtermGetSelection = () => term.getSelection() || dragSel;

      let fitTimer: ReturnType<typeof setTimeout> | null = null;
      const resizeObserver = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (!entry) return;
        const { width, height } = entry.contentRect;
        // Skip fit when container is hidden (display: none).
        if (width === 0 || height === 0) return;
        // Debounce: when a parent toggles display:none → visible, the
        // observer fires with a transient intermediate size (~86px) before
        // the final layout size arrives ~18ms later.  Fitting to the
        // transient size sends a PTY resize that squashes active TUI output
        // (e.g. Claude CLI).  A short debounce ensures we only fit once the
        // layout has stabilised.
        if (fitTimer) clearTimeout(fitTimer);
        fitTimer = setTimeout(() => {
          fitTimer = null;
          fitAddon.fit();
          requestAnimationFrame(() => term.scrollToBottom());
        }, 50);
      });
      resizeObserver.observe(containerRef.current!);

      return () => {
        if (fitTimer) clearTimeout(fitTimer);
        resizeObserver.disconnect();
        container.removeEventListener("mousedown", onDragMouseDown);
        document.removeEventListener("mouseup", onDragMouseUp, true);
        if (xtermEl) delete xtermEl._xtermGetSelection;
      };
    }

    const cleanup = init();

    return () => {
      disposed = true;
      cleanup.then((fn) => fn?.());
      xtermRef.current?.dispose();
      xtermRef.current = null;
    };
  }, [containerRef, onInput, onResize]); // colors excluded — handled by effect below

  // Update xterm theme at runtime when palette changes (no terminal re-creation).
  // Also override .xterm-bg-0 for light themes: the theme `black` must stay dark
  // for foreground text (\x1b[30m), but as a background (\x1b[40m) it should
  // blend with the light terminal background instead of rendering harsh black blocks.
  const bgStyleRef = useRef<HTMLStyleElement | null>(null);
  useEffect(() => {
    if (xtermRef.current) {
      xtermRef.current.options.theme = buildXTermTheme(colors);
    }
    if (!colors.isDark) {
      if (!bgStyleRef.current) {
        bgStyleRef.current = document.createElement("style");
        document.head.appendChild(bgStyleRef.current);
      }
      bgStyleRef.current.textContent = `.xterm-bg-0 { background-color: ${colors.sidebar} !important; }`;
    } else if (bgStyleRef.current) {
      bgStyleRef.current.textContent = "";
    }
  }, [colors]);

  // Update xterm font size at runtime.
  useEffect(() => {
    if (xtermRef.current && termFontSize != null) {
      xtermRef.current.options.fontSize = termFontSize;
      fitAddonRef.current?.fit();
    }
  }, [termFontSize]);

  return { write, clear, xtermRef };
}
