import { useCallback, useEffect, useRef } from "react";
import type { RefObject } from "react";
import "@xterm/xterm/css/xterm.css";
import { type ColorPalette, fonts } from "../theme";

// Inject a one-time style to hide the xterm scrollbar so the FitAddon
// uses the full container width (macOS overlay scrollbars report 0 width
// but the FitAddon may still reserve space).
let scrollbarStyleInjected = false;
function injectScrollbarStyle() {
  if (scrollbarStyleInjected) return;
  scrollbarStyleInjected = true;
  // Use the same scrollbar appearance as the rest of the app (set in ThemeContext).
  // Just ensure the xterm viewport doesn't hide it.
  const style = document.createElement("style");
  style.textContent = `.xterm-viewport { scrollbar-width: thin; }`;
  document.head.appendChild(style);
}

function buildXTermTheme(colors: ColorPalette) {
  return {
    background: colors.sidebar,
    foreground: colors.text,
    cursor: colors.cursor,
    cursorAccent: colors.isDark ? "#000000" : "#ffffff",
    selectionBackground: colors.isDark ? "#214283" : "#a6d2ff",
    selectionForeground: colors.isDark ? undefined : "#000000",
  };
}

interface UseXTerminalOptions {
  containerRef: RefObject<HTMLDivElement | null>;
  colors: ColorPalette;
  fontSize?: number;
  onInput: (data: string) => void;
  onResize: (cols: number, rows: number) => void;
}

/**
 * Manages xterm.js lifecycle: lazy init, fit, resize observation, and cleanup.
 * Returns a `write` callback for pushing data into the terminal and a ref to
 * the underlying Terminal instance.
 */
export function useXTerminal({
  containerRef,
  colors,
  fontSize: termFontSize,
  onInput,
  onResize,
}: UseXTerminalOptions) {
  const xtermRef = useRef<import("@xterm/xterm").Terminal | null>(null);
  const fitAddonRef = useRef<import("@xterm/addon-fit").FitAddon | null>(null);

  const write = useCallback((data: Uint8Array | string) => {
    const term = xtermRef.current;
    if (!term) return;
    term.write(data, () => {
      // Always scroll to bottom after write. Claude CLI uses cursor
      // positioning for its status line which can leave the viewport
      // scrolled up.
      term.scrollToBottom();
    });
  }, []);

  const clear = useCallback(() => {
    xtermRef.current?.clear();
    xtermRef.current?.reset();
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    let disposed = false;

    async function init() {
      const { Terminal: XTerm } = await import("@xterm/xterm");
      const { FitAddon } = await import("@xterm/addon-fit");
      const { WebLinksAddon } = await import("@xterm/addon-web-links");

      if (disposed) return;

      const term = new XTerm({
        cursorBlink: true,
        fontSize: termFontSize ?? 13,
        fontFamily: fonts.mono,
        theme: buildXTermTheme(colors),
      });

      const fitAddon = new FitAddon();
      fitAddonRef.current = fitAddon;
      term.loadAddon(fitAddon);
      term.loadAddon(new WebLinksAddon());

      injectScrollbarStyle();
      term.open(containerRef.current!);

      // Pin scrollbar width to 8px (thin scrollbar).
      // Without this, xterm.js may compute 0 (macOS overlay) or 15px (default).
      const core = (term as any)._core;
      if (core?.viewport) {
        Object.defineProperty(core.viewport, "scrollBarWidth", {
          get: () => 8,
          set: () => {},
          configurable: true,
        });
      }

      fitAddon.fit();

      xtermRef.current = term;

      onResize(term.cols, term.rows);

      term.onData((data) => {
        // Filter out Cursor Position Report responses (ESC[row;colR)
        // generated by xterm.js in response to DSR queries (ESC[6n).
        // These can appear as literal text (e.g. "1;14R") in TUI apps
        // when they arrive at unexpected times during startup.
        if (/^\x1b\[\d+;\d+R$/.test(data)) return;
        onInput(data);
      });

      term.onResize(({ cols, rows }) => {
        onResize(cols, rows);
      });

      // Copy selected text to clipboard automatically.
      term.onSelectionChange(() => {
        const sel = term.getSelection();
        if (sel) navigator.clipboard.writeText(sel).catch(() => {});
      });

      let fitTimer: ReturnType<typeof setTimeout> | null = null;
      const resizeObserver = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (!entry) return;
        const { width, height } = entry.contentRect;
        // Skip fit when container is hidden (display: none).
        if (width === 0 || height === 0) return;
        // Debounce: when a parent toggles display:none → visible, the
        // observer fires with a transient intermediate size (~86px) before
        // the final layout size arrives ~18ms later.  Fitting to the
        // transient size sends a PTY resize that squashes active TUI output
        // (e.g. Claude CLI).  A short debounce ensures we only fit once the
        // layout has stabilised.
        if (fitTimer) clearTimeout(fitTimer);
        fitTimer = setTimeout(() => {
          fitTimer = null;
          fitAddon.fit();
          requestAnimationFrame(() => term.scrollToBottom());
        }, 50);
      });
      resizeObserver.observe(containerRef.current!);

      return () => {
        if (fitTimer) clearTimeout(fitTimer);
        resizeObserver.disconnect();
      };
    }

    const cleanup = init();

    return () => {
      disposed = true;
      cleanup.then((fn) => fn?.());
      xtermRef.current?.dispose();
      xtermRef.current = null;
    };
  }, [containerRef, onInput, onResize]); // colors excluded — handled by effect below

  // Update xterm theme at runtime when palette changes (no terminal re-creation).
  useEffect(() => {
    if (xtermRef.current) {
      xtermRef.current.options.theme = buildXTermTheme(colors);
    }
  }, [colors]);

  // Update xterm font size at runtime.
  useEffect(() => {
    if (xtermRef.current && termFontSize != null) {
      xtermRef.current.options.fontSize = termFontSize;
      fitAddonRef.current?.fit();
    }
  }, [termFontSize]);

  return { write, clear, xtermRef };
}
