import { useCallback, useEffect, useRef } from "react";
import type { RefObject } from "react";
import "@xterm/xterm/css/xterm.css";
import { type ColorPalette, fonts } from "../theme";

// Inject a one-time style to hide the xterm scrollbar so the FitAddon
// uses the full container width (macOS overlay scrollbars report 0 width
// but the FitAddon may still reserve space).
let scrollbarStyleInjected = false;
function injectScrollbarStyle() {
  if (scrollbarStyleInjected) return;
  scrollbarStyleInjected = true;
  const style = document.createElement("style");
  style.textContent = `.xterm-viewport::-webkit-scrollbar { width: 0; height: 0; }
.xterm-viewport { scrollbar-width: none; }`;
  document.head.appendChild(style);
}

function buildXTermTheme(colors: ColorPalette) {
  return {
    background: colors.sidebar,
    foreground: colors.text,
    cursor: colors.cursor,
    cursorAccent: colors.isDark ? "#000000" : "#ffffff",
    selectionBackground: colors.isDark ? "#214283" : "#a6d2ff",
    selectionForeground: colors.isDark ? undefined : "#000000",
  };
}

interface UseXTerminalOptions {
  containerRef: RefObject<HTMLDivElement | null>;
  colors: ColorPalette;
  onInput: (data: string) => void;
  onResize: (cols: number, rows: number) => void;
}

/**
 * Manages xterm.js lifecycle: lazy init, fit, resize observation, and cleanup.
 * Returns a `write` callback for pushing data into the terminal and a ref to
 * the underlying Terminal instance.
 */
export function useXTerminal({
  containerRef,
  colors,
  onInput,
  onResize,
}: UseXTerminalOptions) {
  const xtermRef = useRef<import("@xterm/xterm").Terminal | null>(null);

  const write = useCallback((data: Uint8Array | string) => {
    xtermRef.current?.write(data);
  }, []);

  const clear = useCallback(() => {
    xtermRef.current?.clear();
    xtermRef.current?.reset();
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    let disposed = false;

    async function init() {
      const { Terminal: XTerm } = await import("@xterm/xterm");
      const { FitAddon } = await import("@xterm/addon-fit");
      const { WebLinksAddon } = await import("@xterm/addon-web-links");

      if (disposed) return;

      const term = new XTerm({
        cursorBlink: true,
        fontSize: 13,
        fontFamily: fonts.mono,
        theme: buildXTermTheme(colors),
      });

      const fitAddon = new FitAddon();
      term.loadAddon(fitAddon);
      term.loadAddon(new WebLinksAddon());

      injectScrollbarStyle();
      term.open(containerRef.current!);

      // xterm.js falls back to 15px scrollbar width when the computed value
      // is 0 (macOS overlay scrollbars). Pin it to 0 so the FitAddon uses
      // the full container width. The CSS above hides the scrollbar visually
      // while preserving mouse-wheel scrolling.
      const core = (term as any)._core;
      if (core?.viewport) {
        Object.defineProperty(core.viewport, "scrollBarWidth", {
          get: () => 0,
          set: () => {},
          configurable: true,
        });
      }

      fitAddon.fit();

      xtermRef.current = term;

      onResize(term.cols, term.rows);

      term.onData((data) => {
        // Filter out Cursor Position Report responses (ESC[row;colR)
        // generated by xterm.js in response to DSR queries (ESC[6n).
        // These can appear as literal text (e.g. "1;14R") in TUI apps
        // when they arrive at unexpected times during startup.
        if (/^\x1b\[\d+;\d+R$/.test(data)) return;
        onInput(data);
      });

      term.onResize(({ cols, rows }) => {
        onResize(cols, rows);
      });

      // Copy selected text to clipboard automatically.
      term.onSelectionChange(() => {
        const sel = term.getSelection();
        if (sel) navigator.clipboard.writeText(sel).catch(() => {});
      });

      const resizeObserver = new ResizeObserver(() => {
        fitAddon.fit();
        // Scroll after fit reflow so terminal shows latest output on resize
        // (e.g. switching from terminal-only to split mode).
        requestAnimationFrame(() => term.scrollToBottom());
      });
      resizeObserver.observe(containerRef.current!);

      return () => {
        resizeObserver.disconnect();
      };
    }

    const cleanup = init();

    return () => {
      disposed = true;
      cleanup.then((fn) => fn?.());
      xtermRef.current?.dispose();
      xtermRef.current = null;
    };
  }, [containerRef, onInput, onResize]); // colors excluded — handled by effect below

  // Update xterm theme at runtime when palette changes (no terminal re-creation).
  useEffect(() => {
    if (xtermRef.current) {
      xtermRef.current.options.theme = buildXTermTheme(colors);
    }
  }, [colors]);

  return { write, clear, xtermRef };
}
