run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - misspell
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - bin
    - vendor
