version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - vendor
      - third_party$
      - builtin$
      - examples$
