version: 2

project_name: loop

before:
  hooks:
    - go generate ./internal/readme/
    - go mod tidy

builds:
  - id: loop
    main: ./cmd/loop
    binary: loop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: loop
    repository:
      owner: radutopala
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/radutopala/loop
    description: Discord bot powered by Claude that runs AI agents in Docker containers
    license: GPL-3.0
    commit_author:
      name: Radu Topala
      email: radu.topala@trisoft.ro
    install: |
      bin.install "loop"
    test: |
      system "#{bin}/loop", "--help"

release:
  github:
    owner: radutopala
    name: loop
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
